---
newrelic_license_key: 'ddbf949fa59077b2dd7281ab50e43ba13b51b4a4'
newrelic_loglevel: info
newrelic_logfile: /var/log/newrelic/nrsysmond.log
newrelic_proxy: False
newrelic_ssl: "false"
newrelic_ssl_ca_bundle: False
newrelic_ssl_ca_path: False
newrelic_pidfile: /var/run/newrelic/nrsysmond.pid
newrelic_collector_host: collector.newrelic.com
newrelic_timeout: 30
