---
- name: install mysql and dependencies
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
  - mysql-server
  - mysql-client
  - python-mysqldb

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user:
    user: 'root'
    password: '{{ mysql.rootpass }}'
    host: '{{ item }}'
  with_items:
  - '{{ ansible_hostname }}'
  - '127.0.0.1'
  - '::1'
  - 'localhost'

- name: setup mysql credentials for root user
  template:
    src: 'my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: 'root'
    mode: 0600

