---
- name: install mysql and dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
  - mysql-server
  - mysql-client
  - python-mysqldb
  notify: start mysql

- name: update mysql root password for all root accounts
  mysql_user:
    user: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
  - "{{ ansible_hostname }}"
  - localhost
  - 127.0.0.1
  - ::1
