---
- hosts: development
  gather_facts: yes

  vars_files:
    - settings.yml

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - common
    - apache
    - php
    - mysql
    - wordpress
